apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: todo
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: todo
        tier: frontend
        track: stable
    spec:
      containers:
        - name: nginx
          image: "gcr.io/<GCP_PROJECT_ID>/<CI_REGISTRY_GKE_IMAGE>:<VERSION>"
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]